services:
  # Serviço do Banco de Dados PostgreSQL
  postgres-db:
    image: postgres:17
    container_name: postgres-db-container
    restart: unless-stopped
    environment:
      - POSTGRES_USER=meuuser
      - POSTGRES_PASSWORD=minhasenha
      - POSTGRES_DB=meudb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    # --- SEÇÃO NOVA (HEALTHCHECK) ---
    # Isso define um teste de saúde para o contêiner do Postgres.
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U meuuser -d meudb"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Serviço do Backend .NET
  backend-service:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend-service-container
    working_dir: /app/backend
    command: dotnet watch run --urls "http://*:8080"
    ports:
      - "5000:8080"
      - "5001:8081"
    volumes:
      - ./backend:/app/backend
      - ./imagens_itens:/app/uploads
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=true
    depends_on:
      postgres-db:
        condition: service_healthy

  # Serviço do Frontend Vue.js
  frontend-service:
    container_name: frontend-service-container
    build:
      context: ./frontend
      dockerfile: Dockerfile
    working_dir: /app/frontend
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules

  servidor-imagens:
    image: nginx:alpine
    container_name: servidor-imagens-container
    restart: unless-stopped
    ports:
      - "8088:80"
    volumes:
      - ./imagens_itens:/usr/share/nginx/html/images
    read_only: true
    tmpfs:
      - /var/cache/nginx
      - /var/run
      - /tmp

volumes:
  postgres-data:
